SpriteList Class Reference
#include <general.h>
Public Member Functions
SpriteList ()
sf::Sprite * AddSprite (sf::Sprite sprite, std::string id, unsigned int priority)
void RemoveSprite (std::string id)
std::multimap< unsigned int,
*
sf::Sprite * > * getPriorityMap ()
Static Public Member Functions
static SpriteList * getGeneralSpriteList ()
Private Attributes
std::map< std::string,
*
sf::Sprite * > indexMap
std::multimap< unsigned int,
*
sf::Sprite * > priorityMap
Detailed Description
Definition at line 26 of file general.h.
Constructor & Destructor Documentation
SpriteList::SpriteList () [inline]
Definition at line 29 of file general.h.
Member Function Documentation
sf::Sprite * SpriteList::AddSprite (sf::Sprite sprite, std::string id, unsigned int priority)
Returns
Le sprite reset
Definition at line 21 of file general.cpp.
Referenced by WindowEntity::actuateSprite().
SpriteList * SpriteList::getGeneralSpriteList () [static]
Definition at line 7 of file general.cpp.
Referenced by NtsaWindow::actualize(), and WindowEntity::actuateSprite().
std::multimap<unsigned int, sf::Sprite*>* SpriteList::getPriorityMap () [inline]
Definition at line 34 of file general.h.
Referenced by NtsaWindow::actualize().
void SpriteList::RemoveSprite (std::string id)
Note
check 1
Definition at line 49 of file general.cpp.
Field Documentation
std::map<std::string, sf::Sprite*> SpriteList::indexMap [private]
Definition at line 34 of file general.h.
Referenced by AddSprite(), and RemoveSprite().
std::multimap<unsigned int, sf::Sprite*> SpriteList::priorityMap [private]
Definition at line 38 of file general.h.
Referenced by AddSprite(), and RemoveSprite().
The documentation for this class was generated from the following files:
src/General/general.h
src/General/general.cpp