TextureList Class Reference
#include <general.h>
Public Member Functions
TextureList ()
TextureList (std::string filePath)
void loadTextures (std::string filePath)
void showErrors (std::string outfilen=``)
sf::Texture * getTexture (std::string textureID)
Static Public Member Functions
static TextureList * getGeneralTextureList ()
Private Attributes
std::string m_errors
std::map< std::string,
*
sf::Texture > m_textureMap
Detailed Description
Definition at line 41 of file general.h.
Constructor & Destructor Documentation
TextureList::TextureList () [inline]
Definition at line 44 of file general.h.
TextureList::TextureList (std::string filePath)
Note
check 1
Definition at line 73 of file general.cpp.
Member Function Documentation
TextureList * TextureList::getGeneralTextureList () [static]
Definition at line 12 of file general.cpp.
Referenced by WindowEntity::addTexture().
sf::Texture * TextureList::getTexture (std::string textureID)
Definition at line 128 of file general.cpp.
Referenced by WindowEntity::addTexture().
void TextureList::loadTextures (std::string filePath)
Note
check 1
Definition at line 93 of file general.cpp.
Referenced by TextureList().
void TextureList::showErrors (std::string outfilen = ``)
Note
check 1
Definition at line 78 of file general.cpp.
Referenced by loadTextures().
Field Documentation
std::string TextureList::m_errors [private]
Definition at line 53 of file general.h.
Referenced by loadTextures(), and showErrors().
std::map<std::string, sf::Texture> TextureList::m_textureMap [private]
Definition at line 54 of file general.h.
Referenced by getTexture(), and loadTextures().
The documentation for this class was generated from the following files:
src/General/general.h
src/General/general.cpp