Unoise Namespace Reference
Uchronia noise namespace.
Data Structures
struct point2Dui
struct DiamondPermTable
Stock a PermTable `Diamond`.
Typedefs
typedef std::array< unsigned
*
short, 256 > PermTable
typedef std::vector
*
< std::vector< float > > ChunkPoints
Functions
void setSeed (int graine)
void setPermTable (PermTable *perm)
Pas obligatoire, cette fonction permet de changer lambdaPermTable.
void genPermTable (PermTable *, int)
On génère la table de permutation à partir d'un seed.
std::vector< float > getPositionsAround (ChunkPoints *tableau, point2Dui point, int pas, std::array< std::vector< float >, 4 > *pointsEnvironnants=nullptr, bool phase=1)
ChunkPoints diamondSquareNoise (float x, float y, int amplitude, float res, unsigned short subDivisions, int nseed=-1, std::array< float, 4 > *pointsPrincipaux=nullptr, std::array< std::vector< float >, 4 > *pointsEnvironnants=nullptr)
Midpoint displacement noise, ou Diamond square noise (nom latin: carrus diamus)
float perlinNoise (float x, float z, float res, PermTable *perm=nullptr)
Fonction du bruit de perlin (float x, float z, float resolution, table de permutation):
Variables
PermTable * lambdaPermTable =nullptr
int seed =42
Detailed Description
Uchronia noise namespace.
Typedef Documentation
typedef std::vector<std::vector<float> > Unoise::ChunkPoints
Definition at line 100 of file utilities.h.
typedef std::array<unsigned short, 256> Unoise::PermTable
Definition at line 99 of file utilities.h.
Function Documentation
ChunkPoints Unoise::diamondSquareNoise (float x, float y, int amplitude, float res, ushort subDivisions, int nseed, std::array< float, 4 > * pointsPrincipaux, std::array< std::vector< float >, 4 > * pointsEnvironnants)
Midpoint displacement noise, ou Diamond square noise (nom latin: carrus diamus)
Cet algo génère sur une zone memoire donnée un bruit de type midpoint displacement
Note
Vous trouverez des informations sur le fonctionnement interne de cette fonction dans le fichier algoinfos rubrique diamondSquareNoise
Warning
Il est interdit de mettre pos à 1 ou à 0, car ça signifierait que le nombre de point par coté vaut 2
Parameters
x La position du chunk virtuelle X, inutile dans les versions primitives de la fonction
y La position du chunk virtuelle Y, inutile dans les versions primitives de la fonction
amplitude La hauteur maximale d'un point (la valeur minimale est l'opposée de l'amplitude
res La résolution, c'est à dire la rapidité de la réduction du bruit
subDivisions Le nombre de subdivisions appliqués, pour trouver le nombre de points par coté ça fait, calculez: pow(2, subDivisions)+1
Definition at line 232 of file utilities.cpp.
void Unoise::genPermTable (PermTable * pttable, int seed)
On génère la table de permutation à partir d'un seed.
Parameters
pttable pointeur via une table de permutation qui sera générée avec le seed
seed le seed
Definition at line 130 of file utilities.cpp.
Referenced by perlinNoise().
std::vector<float> Unoise::getPositionsAround (ChunkPoints * tableau, point2Dui point, int pas, std::array< std::vector< float >, 4 > * pointsEnvironnants = nullptr, bool phase = 1)
Cette fonction va donner à l'utilisateur la hauteur des quatres points les plus proches
Note
Elle n'est faite que pour être utilisée par DiamondSquareNoise
Warning
Si cette fonction occure un segfault, celà vient probablement du fait que pas ou tableau est à une valeur érronnée
Parameters
tableau Une référence vers le chunk père du point
pas Le nombre de points par lequel on est autorisé à parcourir le chunk (de un
 en un pour les chunk finis, de quatre en quatre pour les chunks qu'il reste à subdiviser deux fois)
phase Détermine si le point est en phase carré ou diamond, ce qui nous donne un indice sur les points l'environnant
Definition at line 171 of file utilities.cpp.
Referenced by diamondSquareNoise().
float Unoise::perlinNoise (float x, float y, float res, PermTable * perm)
Fonction du bruit de perlin (float x, float z, float resolution, table de permutation):
Parameters
x La position X
y La position Z
res La douceur du terrain
perm Le pointeur vers la table de permutation
Warning
La fonction est défective
Definition at line 322 of file utilities.cpp.
void Unoise::setPermTable (PermTable * perm)
Pas obligatoire, cette fonction permet de changer lambdaPermTable.
Definition at line 124 of file utilities.cpp.
void Unoise::setSeed (int graine)
Definition at line 118 of file utilities.cpp.
Referenced by genPermTable().
Variable Documentation
PermTable* Unoise::lambdaPermTable =nullptr
Definition at line 115 of file utilities.cpp.
Referenced by perlinNoise(), and setPermTable().
int Unoise::seed =42
Definition at line 116 of file utilities.cpp.
Referenced by diamondSquareNoise(), perlinNoise(), and setSeed().